### PR TITLE
Fix cross-compilation: add --erl_xcomp_sysroot

### LINKED ISSUE #165: arm64 builds are missing the crypto components
### Issue

The new aarch64 and osx_arm64 builds do not include the crypto component, here's the relevant snippet from the build log

```
2024-06-24T22:08:11.0547590Z *********************************************************************
2024-06-24T22:08:11.0553380Z **********************  APPLICATIONS DISABLED  **********************
2024-06-24T22:08:11.0555590Z *********************************************************************
2024-06-24T22:08:11.0556110Z 
2024-06-24T22:08:11.0558710Z crypto         : Cannot search for ssl; missing cross system root (erl_xcomp_sysroot).
2024-06-24T22:08:11.0630150Z jinterface     : Java compiler disabled by user
2024-06-24T22:08:11.0714910Z odbc           : ODBC library - header check failed
2024-06-24T22:08:11.0783700Z ssh            : Cannot search for ssl; missing cross system root (erl_xcomp_sysroot).
2024-06-24T22:08:11.0859290Z ssl            : Cannot search for ssl; missing cross system root (erl_xcomp_sysroot).
```

Full logs:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/961700/logs/30
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/961700/logs/26

I've noticed the problem when testing rabbitmq-server build, which needs the `crypto` app. 

EDIT: Info about [erl_xcomp_sysroot](https://github.com/erlang/otp/blob/master/HOWTO/INSTALL-CROSS.md#cross-system-root-locations)

### PR DESCRIPTION
**Pull request by danielhollas**
Without specifying the `--erl_xcomp_sysroot` to point to the host sysroot during cross-compilation, erlang is compiled without SSL, which may break downstream packages that require it.

Closes #165

### Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by danielhollas** [comment]
@conda-forge-admin, please rerender

File: recipe/build.sh [hunk 1]
```diff
@@ -79,7 +81,9 @@ fi
 # "Killing not allowed - living nodes in database."
 epmd  -daemon -relaxed_command_check
 cd "${ERL_TOP}/release/tests/test_server"
-${PREFIX}/bin/erl -s ts install -s ts smoke_test batch -s init stop
+${PREFIX}/bin/erl -s ts install -s ts run crypto -s ts smoke_test batch -s init stop
```
Comment (danielhollas) [inline recipe/build.sh:84]:
```suggestion
${PREFIX}/bin/erl -s ts install -s ts run crypto -s ts smoke_test batch -s ts run ssh batch -s ts run ssl sbatch -s init stop
```

**Comment by danielhollas** [comment]
We did a bunch more testing with RabbitMQ for both aarch64 and arm64-osx and things are looking good so I am going to land this. 

I've also successfully ran through the Erlang crypto test suite, both locally and in CI, see #169 for details. I tried to run also ssh and ssl tests, but those test suites are huge and some tests were failing even for the x86 build so I did not pursue this further.

For completeness, here's how to run a subset of AiiDA test suite that requires RabbitMQ (this is for the Erlang 26 since RabbitMQ does not yet support v27)

```
conda create -n rmq rabbitmq-server
conda activate rmq
# This activates some management plugins that are needed for some of the tests
rabbitmq-plugins enable rabbitmq_management
rabbitmq-server # This will run it in a foreground, use `-detached` to run in background
# In separate tab
git clone https://github.com/aiidateam/aiida-core && cd aiida-core
uv venv
uv pip install -e .[pre-commit]
pytest -m "requires_rmq and not requires_psql"
```
